---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/infra/cert-manager-config
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: cert-manager
    - name: bootstrap-infra
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: porkbun-credentials
      namespace: cert-manager
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: porkbun-webhook
      namespace: flux-system
    - apiVersion: apiregistration.k8s.io/v1
      kind: APIService
      name: v1alpha1.acme.amajor.cloud
