---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockchartsalerts
  namespace: stockchartsalerts
  labels:
    app: stockchartsalerts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockchartsalerts
  template:
    metadata:
      labels:
        app: stockchartsalerts
    spec:
      containers:
        - name: stockchartsalerts
          image: ghcr.io/major/stockchartsalerts@sha256:bc8b7bc3eb8d2d06114658ec48f24dccc2f38688e3f20be51b6c49eb10a809f4
          imagePullPolicy: IfNotPresent
          env:
            - name: SENTRY_DSN
              value: "https://3008fcf0dacd6e579b8b1b866942b9f4@o4504556291358720.ingest.us.sentry.io/4510199838539776"
            - name: TZ
              value: "America/New_York"
            - name: DISCORD_WEBHOOK_URLS
              valueFrom:
                secretKeyRef:
                  name: stockchartsalerts-secrets
                  key: discord-webhook-urls
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
