---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - gateway-api-source
  - gateway-api-crds
  - nginx-ingress
  - flux-notifications
  - redis
  - kwatch
